(() => {
const $ = (s,r=document)=>r.querySelector(s);
const app = $('#app');
const cfg = window.SHOP_OS_CONFIG || {};
const icons = {command:'⌁',dispatch:'▦',production:'⚡',techs:'👤',techMgmt:'★',products:'◈',outlook:'↧',brain:'🧠',whatif:'?',timeline:'≡',mobile:'▱'};
const names = {command:'Command',dispatch:'Dispatch',production:'Production',techs:'Technicians',techMgmt:'Tech Mgmt',products:'Products',outlook:'Outlook',brain:'Shop Brain',whatif:'What If',timeline:'Timeline',mobile:'Mobile'};
const state = {view:'command', data:{}, selectedTech:null, drawer:null, search:'', notices:[], lastSync:'Never', connected:false};
const uuid = ()=>'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)});
const esc = v => String(v ?? '').replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const num = v => Number(v||0);
const dateOnly = d => (d?new Date(d):new Date()).toISOString().slice(0,10);
const today = dateOnly();
const fmtDate = d => { if(!d) return ''; const x=new Date(d+'T00:00:00'); return x.toLocaleDateString(undefined,{month:'short',day:'numeric'}); };
const shortId = id => (id||'').slice(0,6);
const nameOf = (id, arr, fallback='Unassigned') => (arr||[]).find(x=>x.id===id)?.name || fallback;
const statusName = job => nameOf(job.status_id, state.data.statuses, job.status || 'Scheduled');
const productName = id => nameOf(id, state.data.products, 'Other / Manual Entry');
const productsForJob = job => {
  const lines = (state.data.job_products||[]).filter(jp=>jp.job_id===job.id).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).map(jp=>productName(jp.product_id));
  if(lines.length) return lines;
  return [productName(job.product_id)];
};
const jobTitle = job => `${productsForJob(job).join(' + ')}`;
const ro = job => job.ro || job.ro_number || job.ticket || `Job ${shortId(job.id)}`;
const techName = job => nameOf(job.technician_id, state.data.technicians);
const isCompleted = job => /complete|done|closed/i.test(statusName(job)) || !!job.production_completed_at;
const isStarted = job => /progress|started|working/i.test(statusName(job)) || !!job.production_started_at;
const isPaused = job => /pause|hold/i.test(statusName(job)) || !!job.pause_started_at;
const isRoadblocked = job => /road|wait|delay|blocked|hold/i.test(statusName(job)) || !!job.delay_reason_id;
const book = job => num(job.book_hours) || (state.data.job_products||[]).filter(x=>x.job_id===job.id).reduce((s,x)=>s+num(x.book_hours),0);
const actual = job => num(job.actual_hours)||num(job.active_time_hours)||0;
const allJobs = () => (state.data.jobs||[]);
const activeJobs = () => allJobs().filter(j=>!isCompleted(j) && (isStarted(j)||isPaused(j)||isRoadblocked(j)));
const todayJobs = () => allJobs().filter(j=>j.scheduled_date===today && !isCompleted(j));
const productionJobs = () => allJobs().filter(j => !isCompleted(j) && (j.technician_id || isStarted(j) || isRoadblocked(j)) && book(j)>0).sort((a,b)=>String(a.scheduled_date||'').localeCompare(String(b.scheduled_date||'')) || String(a.start_time||'').localeCompare(String(b.start_time||'')));
const completedJobs = () => allJobs().filter(isCompleted);
const risk = job => { const b=book(job), a=actual(job); if(isRoadblocked(job)) return 'critical'; if(b && a>b*1.25) return 'critical'; if(b && a>b*.8 && !isCompleted(job)) return 'risk'; if(/watch/i.test(job.qc||'')) return 'risk'; return 'ok'; };
const riskLabel = r => r==='critical'?'Critical':r==='risk'?'Watch':'On Track';
function supa(path, opts={}){
  if(!cfg.SUPABASE_URL || !cfg.SUPABASE_ANON_KEY) return Promise.resolve({data:null,error:'Missing Supabase env'});
  return fetch(`${cfg.SUPABASE_URL.replace(/\/$/,'')}/rest/v1/${path}`,{
    ...opts,
    headers:{apikey:cfg.SUPABASE_ANON_KEY,Authorization:`Bearer ${cfg.SUPABASE_ANON_KEY}`,'Content-Type':'application/json','Prefer':'return=representation',...(opts.headers||{})}
  }).then(async r=>({data: r.status===204?[]: await r.json().catch(()=>null), error: r.ok?null:(await r.text().catch(()=>r.statusText))})).catch(e=>({data:null,error:e.message}));
}
async function select(table, limit=1000){ const {data,error}=await supa(`${table}?select=*&limit=${limit}`); return Array.isArray(data)?data:[]; }
async function patch(table,id,body){ const {data,error}=await supa(`${table}?id=eq.${id}`,{method:'PATCH',body:JSON.stringify(body)}); if(error) toast('Update failed'); return data; }
async function insert(table,body){ const {data,error}=await supa(`${table}`,{method:'POST',body:JSON.stringify(body)}); if(error) toast('Create failed'); return data; }
function sample(){
 const company='demo';
 const techs=['BRAD MGR*','MATT','WAYNE','BRANNAN','BOBBY','TYLER'].map((name,i)=>({id:'t'+i,name,role:i===0?'Manager':'Technician',active:true,efficiency_goal:110,company_id:company}));
 const sts=['Scheduled','In Progress','Roadblocked','Paused','Completed'].map((name,i)=>({id:'s'+i,name,company_id:company}));
 const prods=['F-250 AirLift + Wireless One','Jeep roof KC lights','37” Tire Balance Set','B&W Turnoverball Install','Camper Shell Install','Spray in Bedliner','Tonneau Cover Install'].map((name,i)=>({id:'p'+i,name,book_hours:[4,3,1.3,2,2,1.5,1][i],labor_price:140,active:true,company_id:company}));
 const jobs=[
  ['46218','Patrick McNulty','F-250',0,1,0,4],['46220','Tyler Shumate','Jeep',1,2,1,3],['46221','Dylan','GM 1500',2,0,2,1.3],['46222','Skylar','F-250',3,1,3,2],['46224','Ethan','Camper Shell',4,0,4,2],['0520c7','Angie Young','Vehicle TBD',1,0,1,2],['8672a5','150 Spray In 495.00','Vehicle TBD',5,0,0,3]
 ].map((x,i)=>({id:'j'+i,customer:x[1],vehicle:x[2],product_id:prods[x[3]].id,technician_id:techs[x[4]].id,status_id:sts[x[5]].id,scheduled_date:today,start_time:['08:00','08:30','09:15','10:00','11:30'][i%5],book_hours:x[6],actual_hours:i<4?x[6]*(.8+i*.15):0,company_id:company,production_started_at:i===0?new Date().toISOString():null, delay_reason_id: x[5]===2?'d1':null}));
 return {companies:[{id:company,name:'H&H Truck & Outdoor'}],technicians:techs,statuses:sts,products:prods,jobs,job_products:jobs.map(j=>({id:'jp'+j.id,job_id:j.id,product_id:j.product_id,book_hours:j.book_hours,labor_price:j.book_hours*140})),job_helpers:[],technician_attendance:[],audit_logs:[],app_notifications:[],comeback_rework:[],delay_reasons:[{id:'d1',name:'Waiting on customer approval'}],outlook_settings:[]};
}
async function load(silent=false){
 const y = $('.main')?.scrollTop || 0;
 if(!cfg.SUPABASE_URL || !cfg.SUPABASE_ANON_KEY){ state.data=sample(); state.connected=false; state.lastSync=new Date().toLocaleTimeString(); render(); $('.main') && ($('.main').scrollTop=y); return; }
 const tables=['companies','technicians','statuses','products','jobs','job_products','job_helpers','technician_attendance','audit_logs','app_notifications','comeback_rework','delay_reasons','outlook_settings'];
 const results = await Promise.all(tables.map(t=>select(t, t==='jobs'?1500:1000)));
 state.data = Object.fromEntries(tables.map((t,i)=>[t,results[i]]));
 state.connected=true; state.lastSync=new Date().toLocaleTimeString();
 if(!state.selectedTech) state.selectedTech=(state.data.technicians||[]).find(t=>t.active)?.id;
 deriveNotices(); render(); $('.main') && ($('.main').scrollTop=y);
}
function deriveNotices(){
 const live = (state.data.app_notifications||[]).slice().sort((a,b)=>new Date(b.created_at||0)-new Date(a.created_at||0)).slice(0,8).map(n=>({title:n.title,body:n.body,type:n.type}));
 const rb = allJobs().filter(j=>!isCompleted(j)&&isRoadblocked(j)).map(j=>({title:'Pending Roadblock',body:`${techName(j)} needs attention on ${ro(j)} · ${jobTitle(j)}`,type:'critical'}));
 const atRisk = allJobs().filter(j=>!isCompleted(j)&&risk(j)!=='ok').slice(0,4).map(j=>({title:'Job At Risk',body:`${ro(j)} · ${jobTitle(j)} is ${riskLabel(risk(j))}.`,type:'warn'}));
 state.notices=[...rb,...atRisk,...live].slice(0,10);
}
function toast(msg){ const t=document.createElement('div'); t.className='toast'; t.textContent=msg; document.body.appendChild(t); setTimeout(()=>t.remove(),2200); }
function shell(content){
 app.innerHTML=`<div class="app"><aside class="dock"><div class="logo">H&H</div>${Object.keys(names).map(k=>`<button class="navbtn ${state.view===k?'active':''}" data-view="${k}">${icons[k]}<span>${names[k]}</span></button>`).join('')}</aside><main class="main">${content}</main><aside class="rail">${rail()}</aside></div>${state.drawer?drawer(state.drawer):''}`;
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;state.drawer=null;render();});
 bindCommon();
}
function header(title, subtitle='') {return `<div class="topline"><div><h1 class="h1">${title}</h1><div class="sub">${subtitle||`Last sync ${state.lastSync} · ${allJobs().length} live jobs · ${(state.data.job_products||[]).length} job products`}</div></div><div><button class="btn" id="refreshBtn">Refresh</button> <button class="btn" id="clearBtn">Clear Notifications</button></div></div>`}
function rail(){ const cap=capacity(); return `<h2 class="sectionTitle">Action Queue</h2>${(state.notices||[]).length?state.notices.map(n=>`<div class="queueItem ${n.type==='critical'?'critical':n.type==='warn'?'warn':''}"><b>${esc(n.title)}</b><p>${esc(n.body)}</p></div>`).join(''):'<div class="empty">No current actions.</div>'}<h3>Pulse</h3>${[['Active jobs',activeJobs().length],['At risk',allJobs().filter(j=>!isCompleted(j)&&risk(j)!=='ok').length],['Today capacity',cap+'%'],['Booked today',todayJobs().reduce((s,j)=>s+book(j),0).toFixed(1)]].map(x=>`<div class="timelineRow" style="grid-template-columns:90px 1fr"><div class="num" style="font-size:28px">${x[1]}</div><div>${x[0]}</div></div>`).join('')}`}
function capacity(){ const total=todayJobs().reduce((s,j)=>s+book(j),0); const techs=(state.data.technicians||[]).filter(t=>t.active&&/tech|manager/i.test(t.role||'tech')).length||1; return Math.round(total/(techs*8)*100); }
function command(){
 const cap=capacity(), labor=todayJobs().reduce((s,j)=>s+num(j.labor_sold||book(j)*140),0), road=allJobs().filter(j=>!isCompleted(j)&&isRoadblocked(j)).length;
 const timeline=productionJobs().slice(0,6);
 return shell(`${header('V2 Command Center','Live production control, technician flow, roadblocks, approvals, capacity, and shop timeline in one screen.')}<section class="hero"><div class="card mission"><h2 class="h1 glowText">Good morning, Cameron.</h2><p class="sub">${state.connected?'Live Supabase data is active.':'Demo mode. Add Supabase env vars to go live.'}</p><div class="chips"><span class="chip">Live dispatch</span><span class="chip">Roadblock control</span><span class="chip">Helper sessions</span><span class="chip">Mobile-first tech view</span><span class="chip">No spreadsheet feel</span></div></div><div class="metricgrid"><div class="metric"><div class="num">${cap}%</div><div class="label">Booked capacity</div></div><div class="metric"><div class="num">$${(labor/1000).toFixed(1)}k</div><div class="label">Projected labor</div></div><div class="metric"><div class="num">${road}</div><div class="label">Roadblocks</div></div><div class="metric"><div class="num">${activeJobs().length}</div><div class="label">Active jobs</div></div></div></section><section class="layout2"><div class="card pad"><h2 class="sectionTitle">Live Production Timeline</h2>${timeline.map(j=>`<div class="timelineRow" data-open="${j.id}"><div class="time">${esc((j.start_time||'').slice(0,5)||'—')}</div><div><b>${esc(ro(j))} · ${esc(jobTitle(j))}</b><div class="small">${esc(techName(j))} · ${esc(j.customer)} · ${esc(j.vehicle)}</div></div><span class="pill ${risk(j)==='critical'?'red':risk(j)==='risk'?'amber':'green'}">${esc(statusName(j))}</span></div>`).join('')||'<p class="empty">No production jobs.</p>'}</div><div class="card pad"><h2 class="sectionTitle">Dispatch Actions</h2><p class="small">One-tap manager actions. These update your live V1 jobs table where possible.</p><button class="btn primary" id="simRoad">Flag Top Job Roadblock</button><br><br><button class="btn" id="completeRandom">Complete Top Active Job</button><br><br><button class="btn ghost" id="clearActivity">Clear Local Activity Feed</button></div></section><section class="card pad" style="margin-top:18px"><h2 class="sectionTitle">Technician Flow</h2><div class="techflow">${(state.data.technicians||[]).filter(t=>t.active).map(techFlowCard).join('')}</div></section>`);
}
function techFlowCard(t){ const jobs=productionJobs().filter(j=>j.technician_id===t.id); const hrs=jobs.reduce((s,j)=>s+book(j),0), pct=Math.min(100,Math.round(hrs/8*100)); return `<div class="card techcard" data-tech="${t.id}"><div class="avatar">${esc((t.name||'?')[0])}</div><h3>${esc(t.name)}</h3><div class="small">${esc(t.role||'Technician')}</div><div class="bar"><i style="width:${pct}%"></i></div><p><b>${hrs.toFixed(1)} booked hrs</b> · ${jobs.length} jobs</p><div class="small">${jobs[0]?`Current/Next: ${esc(jobTitle(jobs[0]))}`:'Available'}</div></div>`; }
function dispatch(){ const techs=(state.data.technicians||[]).filter(t=>t.active); return shell(`${header('Live Dispatch','Swim lanes show actionable production only: active work, roadblocks, paused jobs, and today’s scheduled production.')}<div class="dispatch">${techs.map(t=>{const jobs=productionJobs().filter(j=>j.technician_id===t.id).slice(0,8); const hrs=jobs.reduce((s,j)=>s+book(j),0); return `<div class="card pad laneBig"><h2>${esc(t.name)} <span class="small" style="float:right">${jobs.length} jobs · ${hrs.toFixed(1)}h</span></h2>${jobs.length?jobs.map(jobCard).join(''):'<p class="empty">No actionable work.</p>'}</div>`}).join('')}</div>`); }
function jobCard(j){return `<div class="jobcard ${risk(j)}" data-open="${j.id}"><button class="pill watch" data-open="${j.id}">Watch</button><div class="jobtitle">${esc(ro(j))} · ${esc(jobTitle(j))}</div><div>${esc(j.customer)} · ${esc(j.vehicle)}</div><div class="small">${esc(techName(j))} · ${esc(statusName(j))} · ${book(j).toFixed(2)}h · ${fmtDate(j.scheduled_date)}</div><div style="margin-top:12px"><button class="btn mini" data-action="start" data-id="${j.id}">Start</button> <button class="btn mini" data-action="roadblock" data-id="${j.id}">Roadblock</button> <button class="btn mini" data-action="complete" data-id="${j.id}">Complete</button></div></div>`}
function production(){ const jobs=productionJobs().filter(j=>!state.search || JSON.stringify(j).toLowerCase().includes(state.search.toLowerCase()) || jobTitle(j).toLowerCase().includes(state.search.toLowerCase())); return shell(`${header('Production Jobs')}<input class="search" id="search" value="${esc(state.search)}" placeholder="Search RO, customer, vehicle, product..."><div style="margin:14px 0"><button class="btn filter">All Open</button> <button class="btn filter">In Progress</button> <button class="btn filter">Scheduled</button> <button class="btn filter">Roadblocked</button></div>${jobs.map(jobCard).join('')||'<p class="empty">No jobs found.</p>'}`); }
function techs(){ return shell(`${header('Technician Flow')}<div class="techflow">${(state.data.technicians||[]).filter(t=>t.active).map(techFlowCard).join('')}</div>`); }
function techMgmt(){ const techs=(state.data.technicians||[]).filter(t=>t.active); const tid=state.selectedTech||techs[0]?.id; const t=techs.find(x=>x.id===tid)||techs[0]; const jobs=completedJobs().filter(j=>j.technician_id===t?.id).sort((a,b)=>new Date(b.production_completed_at||b.updated_at||0)-new Date(a.production_completed_at||a.updated_at||0)); const assigned=allJobs().filter(j=>j.technician_id===t?.id); const stats=techStats(t?.id); return shell(`${header('Tech Management')}<select class="selectNative" id="techSelect">${techs.map(x=>`<option value="${x.id}" ${x.id===t?.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select><div class="statrow"><div class="bigstat"><div class="num">${stats.eff}%</div><div class="label">Lifetime efficiency</div></div><div class="bigstat"><div class="num">${stats.completed}</div><div class="label">Completed jobs</div></div><div class="bigstat"><div class="num">${stats.roadblocks}</div><div class="label">Roadblocks</div></div><div class="bigstat"><div class="num">${stats.comebacks}</div><div class="label">Comebacks</div></div></div><div class="split"><div class="card pad"><h2>Install Time History</h2><table class="table"><tr><th>Job</th><th>Product</th><th>Book</th><th>Actual</th><th>Eff</th><th>Status</th></tr>${(jobs.length?jobs:assigned).slice(0,16).map(j=>`<tr data-open="${j.id}"><td>${esc(ro(j))}</td><td>${esc(jobTitle(j))}</td><td>${book(j).toFixed(2)}</td><td>${actual(j)?actual(j).toFixed(2):'—'}</td><td>${actual(j)?Math.round(book(j)/actual(j)*100)+'%':'—'}</td><td>${esc(statusName(j))}</td></tr>`).join('')}</table></div><div class="card pad"><h2>Product Strengths</h2><table class="table"><tr><th>Product</th><th>Jobs</th><th>Book</th><th>Actual</th><th>Eff</th></tr>${productStrengths(t?.id).map(r=>`<tr><td>${esc(r.name)}</td><td>${r.jobs}</td><td>${r.book.toFixed(1)}</td><td>${r.actual.toFixed(1)}</td><td>${r.actual?Math.round(r.book/r.actual*100)+'%':'—'}</td></tr>`).join('')}</table><br><button class="btn" id="exportCsv">Export CSV</button></div></div>`); }
function techStats(tid){ const jobs=completedJobs().filter(j=>j.technician_id===tid); const b=jobs.reduce((s,j)=>s+book(j),0), a=jobs.reduce((s,j)=>s+(actual(j)||book(j)),0); return {completed:jobs.length,eff:a?Math.round(b/a*100):0,roadblocks:allJobs().filter(j=>j.technician_id===tid && isRoadblocked(j)).length,comebacks:(state.data.comeback_rework||[]).filter(c=>c.original_technician_id===tid||c.rework_technician_id===tid).length}; }
function productStrengths(tid){ const map={}; completedJobs().filter(j=>j.technician_id===tid).forEach(j=>productsForJob(j).forEach(p=>{map[p]??={name:p,jobs:0,book:0,actual:0}; map[p].jobs++; map[p].book+=book(j); map[p].actual+=actual(j)||book(j)})); return Object.values(map).sort((a,b)=>(b.book/(b.actual||b.book))-(a.book/(a.actual||a.book))).slice(0,12); }
function products(){ const rows=(state.data.products||[]).filter(p=>p.active!==false).map(p=>{const jobs=allJobs().filter(j=>productsForJob(j).includes(p.name)); const done=jobs.filter(isCompleted); const b=done.reduce((s,j)=>s+book(j),0), a=done.reduce((s,j)=>s+(actual(j)||book(j)),0); return {...p,jobs:jobs.length,done:done.length,eff:a?Math.round(b/a*100):0};}); return shell(`${header('Product Intelligence')}<div class="grid">${rows.map(p=>`<div class="card pad"><h2>${esc(p.name)}</h2><div class="statrow"><div><div class="num">${p.jobs}</div><div class="label">Jobs</div></div><div><div class="num">${p.done}</div><div class="label">Completed</div></div><div><div class="num">${p.book_hours||'—'}</div><div class="label">Base Book</div></div><div><div class="num">${p.eff||'—'}%</div><div class="label">Efficiency</div></div></div></div>`).join('')}</div>`); }
function outlook(){ return shell(`${header('Outlook Import','Import appointments as staging items. V2 should classify them before dispatch.')}<div class="split"><div class="card pad"><h2>Paste Outlook / ICS Text</h2><textarea id="ics" rows="10" placeholder="Paste exported Outlook event text or CSV rows here..."></textarea><br><br><button class="btn primary" id="parseIcs">Preview Import</button></div><div class="card pad"><h2>Import Rules</h2><div class="brainline">Appointment → Estimate → Approve → Production Job</div><div class="brainline">Dispatch only gets assigned jobs with book time.</div><div class="brainline">Calendar fluff stays out of production.</div></div></div><div id="importPreview"></div>`); }
function brain(){ const recs=brainRecs(); return shell(`${header('Shop Brain','Operational recommendations based on V1 live data.')}<div class="card pad"><h2 class="h1 glowText">Today’s Operating Brief</h2>${recs.map(r=>`<div class="brainline">${r}</div>`).join('')}</div>`); }
function brainRecs(){ const cap=capacity(); const r=[]; r.push(cap>100?`Shop is over booked at ${cap}%. Consider moving low-priority work or adding helper coverage.`:`Shop capacity is controlled at ${cap}%.`); const rb=allJobs().filter(j=>!isCompleted(j)&&isRoadblocked(j)); if(rb[0]) r.push(`${techName(rb[0])} has a roadblock on ${ro(rb[0])}. Clear this first.`); const best=(state.data.technicians||[]).map(t=>({t,s:techStats(t.id)})).sort((a,b)=>b.s.eff-a.s.eff)[0]; if(best) r.push(`${best.t.name} is currently strongest by completed-job efficiency at ${best.s.eff}%.`); const topProd=Object.values((state.data.products||[]).reduce((m,p)=>(m[p.name]={name:p.name,count:allJobs().filter(j=>productsForJob(j).includes(p.name)).length},m),{})).sort((a,b)=>b.count-a.count)[0]; if(topProd) r.push(`${topProd.name} is the highest-volume product in the current data set.`); return r; }
function whatif(){ return shell(`${header('What If Engine','Decision simulation using current shop capacity.')}<div class="split"><div class="card pad"><h2>Simulations</h2><button class="btn primary" data-sim="helper">What if we add a helper?</button><br><br><button class="btn" data-sim="move">What if we move one job tomorrow?</button><br><br><button class="btn" data-sim="complete">What if top tech finishes early?</button></div><div class="card pad" id="simResult"><h2>Result</h2><p class="empty">Pick a simulation.</p></div></div>`); }
function timeline(){ const events=[...(state.data.audit_logs||[]).map(a=>({time:a.created_at,title:a.action,body:a.summary})),...allJobs().flatMap(j=>[['production_started_at','Started'],['production_completed_at','Completed'],['updated_at','Updated']].filter(x=>j[x[0]]).map(x=>({time:j[x[0]],title:`${ro(j)} ${x[1]}`,body:`${jobTitle(j)} · ${techName(j)}`})))].sort((a,b)=>new Date(b.time)-new Date(a.time)).slice(0,80); return shell(`${header('Shop Replay Timeline')}<div class="card pad">${events.map(e=>`<div class="timelineRow"><div class="time">${new Date(e.time).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</div><div><b>${esc(e.title)}</b><div class="small">${esc(e.body||'')}</div></div><span class="pill">${new Date(e.time).toLocaleDateString()}</span></div>`).join('')||'<p class="empty">No timeline events.</p>'}</div>`); }
function mobile(){ const j=productionJobs()[0]; return shell(`${header('Technician Cockpit')}<div class="mobileFrame"><div class="phoneScreen">${j?`<div class="small">Technician Cockpit</div><h2>${esc(ro(j))}</h2><h1>${esc(jobTitle(j))}</h1><p>${esc(j.customer)} · ${esc(j.vehicle)}</p><div class="num">${book(j).toFixed(2)}h book time</div><div class="bottomActions"><button class="btn" data-action="start" data-id="${j.id}">Start</button><button class="btn" data-action="roadblock" data-id="${j.id}">Roadblock</button><button class="btn">Pause</button><button class="btn primary" data-action="complete" data-id="${j.id}">Complete</button></div>`:'<p>No current job.</p>'}</div></div>`); }
function drawer(id){ const j=allJobs().find(x=>x.id===id); if(!j) return ''; const helpers=(state.data.job_helpers||[]).filter(h=>h.job_id===id); const audits=(state.data.audit_logs||[]).filter(a=>a.entity_id===id || JSON.stringify(a.metadata||{}).includes(id)).slice(0,12); const left=book(j)-actual(j); return `<div class="drawer"><div class="sheet"><button class="close" id="closeDrawer">×</button><h1>${esc(ro(j))}</h1><h2>${esc(jobTitle(j))}</h2><p>${esc(j.customer)} · ${esc(j.vehicle)}</p><div class="statrow"><div class="bigstat"><div class="label">Status</div><div class="num">${esc(statusName(j))}</div></div><div class="bigstat"><div class="label">Risk</div><div class="num">${riskLabel(risk(j))}</div></div><div class="bigstat"><div class="label">Book</div><div class="num">${book(j).toFixed(2)}</div></div><div class="bigstat"><div class="label">Left</div><div class="num">${isNaN(left)?'—':left.toFixed(1)}</div></div></div><div style="margin-bottom:18px"><button class="btn" data-action="start" data-id="${j.id}">Start</button> <button class="btn" data-action="roadblock" data-id="${j.id}">Roadblock</button> <button class="btn primary" data-action="complete" data-id="${j.id}">Complete</button></div><div class="split"><div class="card pad"><h2>Products</h2>${productsForJob(j).map(p=>`<div class="brainline">${esc(p)}</div>`).join('')}<h2>Active Helpers</h2>${helpers.length?helpers.map(h=>`<div>${esc(nameOf(h.technician_id,state.data.technicians))} · ${esc(h.status)} · ${num(h.actual_hours||h.book_hours).toFixed(2)}h</div>`).join(''):'<p class="empty">No active helpers.</p>'}</div><div class="card pad"><h2>Job Notes</h2><p>${esc(j.notes||'No notes.')}</p><h2>Audit / History</h2>${audits.length?audits.map(a=>`<div class="timelineRow" style="grid-template-columns:70px 1fr"><div class="time">${new Date(a.created_at).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</div><div><b>${esc(a.action)}</b><div class="small">${esc(a.summary||'')}</div></div></div>`).join(''):'<p class="empty">No audit events found.</p>'}</div></div></div></div>`; }
async function jobAction(id,action){ const j=allJobs().find(x=>x.id===id); if(!j) return; const sts=state.data.statuses||[]; const findSt=n=>sts.find(s=>new RegExp(n,'i').test(s.name)); let body={updated_at:new Date().toISOString()};
 if(action==='start'){ const s=findSt('progress|started|working'); if(s) body.status_id=s.id; body.production_started_at=j.production_started_at||new Date().toISOString(); }
 if(action==='complete'){ const s=findSt('complete|done|closed'); if(s) body.status_id=s.id; body.production_completed_at=new Date().toISOString(); body.actual_hours=actual(j)||book(j); }
 if(action==='roadblock'){ const s=findSt('road|wait|hold|pause'); if(s) body.status_id=s.id; body.notes=(j.notes||'')+'\nRoadblock flagged from V2.'; }
 await patch('jobs',id,body); toast(`${action} applied to ${ro(j)}`); await load(true);
}
function bindCommon(){
 $('#refreshBtn') && ($('#refreshBtn').onclick=()=>load()); $('#clearBtn') && ($('#clearBtn').onclick=()=>{state.notices=[];render();}); $('#closeDrawer') && ($('#closeDrawer').onclick=()=>{state.drawer=null;render();});
 document.querySelectorAll('[data-open]').forEach(el=>el.onclick=e=>{ if(e.target.dataset.action) return; state.drawer=el.dataset.open; render(); });
 document.querySelectorAll('[data-action]').forEach(el=>el.onclick=e=>{e.stopPropagation(); jobAction(el.dataset.id,el.dataset.action);});
 document.querySelectorAll('[data-tech]').forEach(el=>el.onclick=()=>{state.selectedTech=el.dataset.tech;state.view='techMgmt';render();});
 $('#search') && ($('#search').oninput=e=>{state.search=e.target.value;render();});
 $('#techSelect') && ($('#techSelect').onchange=e=>{state.selectedTech=e.target.value;render();});
 $('#exportCsv') && ($('#exportCsv').onclick=()=>exportCsv());
 $('#parseIcs') && ($('#parseIcs').onclick=()=>previewImport());
 $('#simRoad') && ($('#simRoad').onclick=()=>{const j=productionJobs()[0]; if(j) jobAction(j.id,'roadblock');});
 $('#completeRandom') && ($('#completeRandom').onclick=()=>{const j=activeJobs()[0]||productionJobs()[0]; if(j) jobAction(j.id,'complete');});
 $('#clearActivity') && ($('#clearActivity').onclick=()=>{state.notices=[];render();});
 document.querySelectorAll('[data-sim]').forEach(b=>b.onclick=()=>{const cap=capacity(); const msg={helper:`Adding one helper to the top job improves projected capacity by about 8–15% and may recover ${(productionJobs()[0]?book(productionJobs()[0])*.25:0).toFixed(1)} hrs.`,move:`Moving one ${book(productionJobs()[0]||{}).toFixed(1)} hr job tomorrow changes capacity from ${cap}% to ${Math.max(0,cap-12)}%.`,complete:`If the strongest tech finishes 30 min early, use them as floating help before assigning a new job.`}[b.dataset.sim]; $('#simResult').innerHTML=`<h2>Result</h2><div class="brainline">${msg}</div>`;});
}
function exportCsv(){ const t=state.data.technicians.find(x=>x.id===state.selectedTech); const rows=completedJobs().filter(j=>j.technician_id===state.selectedTech).map(j=>[ro(j),jobTitle(j),book(j),actual(j),statusName(j)]); const csv='job,product,book,actual,status\n'+rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'})); a.download=`${t?.name||'tech'}-history.csv`; a.click(); }
function previewImport(){ const text=$('#ics').value||''; const lines=text.split(/\n+/).filter(Boolean).slice(0,20); $('#importPreview').innerHTML=`<div class="card pad" style="margin-top:18px"><h2>Import Preview</h2>${lines.map(l=>`<div class="timelineRow"><div class="pill">staged</div><div>${esc(l)}</div><span class="pill amber">needs review</span></div>`).join('')||'<p>No rows pasted.</p>'}</div>`; }
function render(){ const map={command,dispatch,production,techs,techMgmt,products,outlook,brain,whatif,timeline,mobile}; (map[state.view]||command)(); }
window.addEventListener('keydown',e=>{ if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){ e.preventDefault(); const q=prompt('Command Palette: tech, RO, product, roadblocks'); if(!q) return; const tech=(state.data.technicians||[]).find(t=>t.name.toLowerCase().includes(q.toLowerCase())); if(tech){state.selectedTech=tech.id;state.view='techMgmt';render();return;} const job=allJobs().find(j=>JSON.stringify(j).toLowerCase().includes(q.toLowerCase())||jobTitle(j).toLowerCase().includes(q.toLowerCase())); if(job){state.drawer=job.id;render();return;} state.view=/road/i.test(q)?'dispatch':'command'; render(); }});
load(); setInterval(()=>load(true),30000); document.addEventListener('visibilitychange',()=>{if(!document.hidden) load(true)});
})();
